# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: praktikum
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  llama:
    image: ghcr.io/ggerganov/llama.cpp:server
    command: '-m /models/dev-model.gguf --port 8000 --host 0.0.0.0 --ctx-size 2048'
    volumes:
      - ./llm/models:/models
    ports:
      - 8000:8000

  ya-boo-migrate:
    environment:
      BOO_DSN: postgres://postgres:postgres@db:5432/praktikum?sslmode=disable
    build:
      target: ya-boo
    command: '/app/ya-boo migrate -c /app/config.yaml'
    depends_on:
      db:
        condition: service_healthy

  ya-boo:
    environment:
      BOO_DSN: postgres://postgres:postgres@db:5432/praktikum?sslmode=disable
    env_file: .env
    build:
      target: ya-boo
    command: '/app/ya-boo run -c /app/config.yaml'
    depends_on:
      ya-boo-migrate:
        condition: service_completed_successfully
      llama:
        condition: service_started

volumes:
  pgdata:
