name: ya-boo

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    container: golang:1.23

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: praktikum
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: |
          go test
